/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"github.com/gin-gonic/gin"
)

type DepartmentsAPI interface {

	// ListDepartments Get /api/departments
	// Zoznam oddeleni
	ListDepartments(c *gin.Context)
}
