/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"github.com/gin-gonic/gin"
)

type TrainingsAPI interface {

	// CreateTraining Post /api/trainings
	// Vytvorenie skolenia
	CreateTraining(c *gin.Context)

	// DeleteTraining Delete /api/trainings/:trainingId
	// Zrusenie alebo odstranenie skolenia
	DeleteTraining(c *gin.Context)

	// GetTraining Get /api/trainings/:trainingId
	// Detail skolenia
	GetTraining(c *gin.Context)

	// ListTrainings Get /api/trainings
	// Zoznam skoleni
	ListTrainings(c *gin.Context)

	// UpdateTraining Put /api/trainings/:trainingId
	// Uprava skolenia
	UpdateTraining(c *gin.Context)
}
