/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"github.com/gin-gonic/gin"
)

type RegistrationsAPI interface {

	// CreateRegistration Post /api/trainings/:trainingId/registrations
	// Prihlasenie zamestnanca na skolenie
	CreateRegistration(c *gin.Context)

	// DeleteRegistration Delete /api/trainings/:trainingId/registrations/:registrationId
	// Odhlasenie zo skolenia
	DeleteRegistration(c *gin.Context)

	// GetRegistration Get /api/trainings/:trainingId/registrations/:registrationId
	// Detail registracie
	GetRegistration(c *gin.Context)

	// ListRegistrations Get /api/trainings/:trainingId/registrations
	// Zoznam registracii na skolenie
	ListRegistrations(c *gin.Context)

	// UpdateRegistration Put /api/trainings/:trainingId/registrations/:registrationId
	// Uprava registracie
	UpdateRegistration(c *gin.Context)
}
