/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"time"
)

type Training struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Type TrainingType `json:"type"`

	Department string `json:"department"`

	StartAt time.Time `json:"startAt"`

	Capacity int32 `json:"capacity"`

	Lecturer string `json:"lecturer"`

	Location string `json:"location,omitempty"`

	// Online link skolenia; prazdny retazec znamena, ze skolenie je prezencne.
	OnlineLink string `json:"onlineLink,omitempty"`

	Description string `json:"description,omitempty"`

	Requirements string `json:"requirements,omitempty"`

	Status TrainingStatus `json:"status"`

	Occupied int32 `json:"occupied"`

	Waitlisted int32 `json:"waitlisted"`
}
