/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"time"
)

type Registration struct {
	Id string `json:"id"`

	TrainingId string `json:"trainingId"`

	EmployeeId string `json:"employeeId"`

	EmployeeName string `json:"employeeName"`

	EmployeeEmail string `json:"employeeEmail,omitempty"`

	Department string `json:"department,omitempty"`

	Note string `json:"note,omitempty"`

	Status RegistrationStatus `json:"status"`

	RegisteredAt time.Time `json:"registeredAt"`
}
