/*
 * MedEdu API
 *
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * API version: 1.0.0
 * Contact: xcervenkak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mededu

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DepartmentsAPI part of the API
	DepartmentsAPI DepartmentsAPI
	// Routes for the RegistrationsAPI part of the API
	RegistrationsAPI RegistrationsAPI
	// Routes for the TrainingsAPI part of the API
	TrainingsAPI TrainingsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"ListDepartments",
			http.MethodGet,
			"/api/departments",
			handleFunctions.DepartmentsAPI.ListDepartments,
		},
		{
			"CreateRegistration",
			http.MethodPost,
			"/api/trainings/:trainingId/registrations",
			handleFunctions.RegistrationsAPI.CreateRegistration,
		},
		{
			"DeleteRegistration",
			http.MethodDelete,
			"/api/trainings/:trainingId/registrations/:registrationId",
			handleFunctions.RegistrationsAPI.DeleteRegistration,
		},
		{
			"GetRegistration",
			http.MethodGet,
			"/api/trainings/:trainingId/registrations/:registrationId",
			handleFunctions.RegistrationsAPI.GetRegistration,
		},
		{
			"ListRegistrations",
			http.MethodGet,
			"/api/trainings/:trainingId/registrations",
			handleFunctions.RegistrationsAPI.ListRegistrations,
		},
		{
			"UpdateRegistration",
			http.MethodPut,
			"/api/trainings/:trainingId/registrations/:registrationId",
			handleFunctions.RegistrationsAPI.UpdateRegistration,
		},
		{
			"CreateTraining",
			http.MethodPost,
			"/api/trainings",
			handleFunctions.TrainingsAPI.CreateTraining,
		},
		{
			"DeleteTraining",
			http.MethodDelete,
			"/api/trainings/:trainingId",
			handleFunctions.TrainingsAPI.DeleteTraining,
		},
		{
			"GetTraining",
			http.MethodGet,
			"/api/trainings/:trainingId",
			handleFunctions.TrainingsAPI.GetTraining,
		},
		{
			"ListTrainings",
			http.MethodGet,
			"/api/trainings",
			handleFunctions.TrainingsAPI.ListTrainings,
		},
		{
			"UpdateTraining",
			http.MethodPut,
			"/api/trainings/:trainingId",
			handleFunctions.TrainingsAPI.UpdateTraining,
		},
	}
}
