kind: Service
apiVersion: v1
metadata:
  name: kcrp-mededu-webapi
spec:
  selector:
    pod: kcrp-mededu-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port
